# Generated by Django 4.2.16 on 2024-10-07 07:30

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='state',
            field=localflavor.us.models.USStateField(default='NY', max_length=2),
        ),
        migrations.AddField(
            model_name='login',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='login',
            name='address_1',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
