# Generated by Django 4.2.16 on 2024-10-07 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_login_state_login_zip_code_alter_login_address_1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Location',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.location'),
        ),
    ]
