# Generated by Django 4.2.16 on 2024-10-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listing_brand_listing_color_listing_describtion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='describtion',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='transmission',
        ),
        migrations.AddField(
            model_name='listing',
            name='transmisson',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default=None, max_length=24),
        ),
    ]
