# Generated by Django 4.2.16 on 2024-10-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_listing_transmisson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='transmisson',
            new_name='transmission',
        ),
    ]
